### ISSUE TITLE
Uppercase headers such as %Newsgroups% %Message-Id% are not retrieved.

### ISSUE THREAD

**Issue by VV-SH** [RealRaven2000/SmartTemplates#211]
Hi!

In the current version, the %Newsgroups% variable does not work
For example - news://ddt.demos.su/fido7.ru.windows.xp

**Comment by RealRaven2000** [comment]
Can you try using `%newsgroups%` instead?

**Comment by RealRaven2000** [comment]
Here is finally a fixed version - I had to change the way headers were retrieved from a streamed message (due to issue #201)

[smartTemplate-fx-3.14pre6.zip](https://github.com/RealRaven2000/SmartTemplates/files/9542446/smartTemplate-fx-3.14pre6.zip)

To install this prerelease, please download the zip file and drag it into Thunderbird Add-ons Manager (without extracting the files)

**Comment by RealRaven2000** [comment]
Fixed in 3.14 released today
