### ISSUE TITLE
Improvement Request: ST4 > 4.6 Increase font sizes

### ISSUE THREAD

**Issue by MarkyMarkDE** [RealRaven2000/SmartTemplates#299]
please add  our option to change the font size as on the legacy one, especially the font in the textareas are really small and in some tabs e.g. the description in About-Tab is really, really small.
I have good eyes but this is little small for me too :wink:

**Comment by RealRaven2000** [comment]
Ok. It was just a LOT of work to convert the dialog even without these...
 We could add the option without UI first (as a hidden about:config setting)?

**Comment by MarkyMarkDE** [comment]
> Ok. It was just a LOT of work to convert the dialog even without these... We could add the option without UI first (as a hidden about:config setting)?

sure.

Please look at this (original sizes):

![Bildschirmfoto vom 2024-07-15 18-54-39](https://github.com/user-attachments/assets/f1b72db5-0cd8-48e1-8b51-1f467cea82f0)

![Bildschirmfoto vom 2024-07-15 18-54-50](https://github.com/user-attachments/assets/bc222981-699d-4e09-8d56-b7996e453a5a)

![Bildschirmfoto vom 2024-07-15 18-56-47](https://github.com/user-attachments/assets/c82ffb43-625f-405b-886b-6736fd5a264a)

**Comment by RealRaven2000** [comment]
> sure.
> 
> Please look at this (original sizes):

ok looks the same here (2.5k Screens) you want all the template fields + License Key and the description under SmartTemplates Pro larger? A proper accessibility button would increase ALL the fonts. 

what about the text size of the external Template Files list? At the moment it is the same size as the menus on my screen (12px)

the font size of the templates / quote headers is also 12px (but in a Monospaced font) so it makes them look smaller than the labels on the dialogs which are 13.2px (which comes from browser styles showing them as 1.1rem - see preferences.css). We could default text-areas to 1.1rem as well to start with - which would look like this:

![image](https://github.com/user-attachments/assets/3100edd1-29d3-4a3b-a9a2-9929bff8dd7a)

I think the original fonts were this small because the dialog really had trouble showing everything.

By the way, since this dialog is now displayed in a Content Tab, you can zoom in using `CTRL` `+` like on any webpage:

![image](https://github.com/user-attachments/assets/a46d1cae-e687-42a7-8dce-5cb986d3209d)

**Comment by RealRaven2000** [comment]
PS: we just have to make sure the dialog still shows everything when we make the Thunderbird windows really small:

![image](https://github.com/user-attachments/assets/e0f64a1a-c148-42d5-8d1a-483da7f84e7a)

(I added a lot of responsiveness tweaks like hiding labels and decreasing spacing to save a lot of space with small heights / widths.)

**Comment by RealRaven2000** [comment]
For the meantime -here is an interim version with some slighttly increased fonts and better spacing on the support page. Make sure to restart Thunderbird because style sheets are cached:

[smartTemplate-fx-4.6.1pre5.zip](https://github.com/user-attachments/files/16238612/smartTemplate-fx-4.6.1pre5.zip)

Examples:

**Account Templates**

![image](https://github.com/user-attachments/assets/ad15f0eb-2802-45f4-a518-e003fb84b0f1)

**About Screen**

![image](https://github.com/user-attachments/assets/fb14cd9a-a783-421f-b6e9-22691edcba63)

**Support Page**

![image](https://github.com/user-attachments/assets/0d4195c3-85f4-430b-b0bb-f49619955150)

**Licenses**

![image](https://github.com/user-attachments/assets/5cc69d1b-4e0f-41b4-9185-81fc8513009a)

----- 

to install the version above, drag the archive (zip file) into Thunderbird Add-ons manager - do not unpack contents as then it won't install. style sheet changes may not reflect immediately, so restart of Thunderbird is advised.

**Comment by MarkyMarkDE** [comment]
thank you, really much better.
The green / red note below the license area can also have the new size please

**Comment by RealRaven2000** [comment]
> thank you, really much better. The green / red note below the license area can also have the new size please

[smartTemplate-fx-4.6.1pre7.zip](https://github.com/user-attachments/files/16240797/smartTemplate-fx-4.6.1pre7.zip)

try this one?

**Comment by MarkyMarkDE** [comment]
> > thank you, really much better. The green / red note below the license area can also have the new size please
> 
> [smartTemplate-fx-4.6.1pre7.zip](https://github.com/user-attachments/files/16240797/smartTemplate-fx-4.6.1pre7.zip)
> 
> try this one?

yes, thank you much. So we dont need a sprecial setting to chane font size for now :wink:

**Comment by RealRaven2000** [comment]
OK, I have just released 4.6.1 (with a few other tweaks). it should be landing on ATN shortly...

**Comment by RealRaven2000** [comment]
Implemented in 4.6.1 - published 16/07/2024
